config/routes.rb
Rails.application.routes.draw do

    require 'sidekiq/web'
    require 'sidekiq/cron/web'

    mount Sidekiq::Web => '/admin/sidekiq/report'

    get '/404', to: 'error#not_found_error', as: 'not_found_error', via: :all
    get '/500', to: 'error#internal_server_error', as: 'internal_server_error', via: :all

    root 'home#index'
    get 'home/index'
    get 'search/all', to:'home#search', as: 'search'
    get 'search/items', to: 'home#search_items', as: 'search_items'
    get 'search/requests', to: 'home#search_requests', as: 'search_requests'
    get 'search/users', to: 'home#search_users', as: 'search_users'
    post 'notification/send', to: 'home#notification_getway', as: 'notification_getway'

    get '/session', to: 'session#index', as: 'session'
    get '/session/profile', to: 'session#index', as: 'session_profile'
    get '/session/items', to: 'session#index', as: 'session_items'
    get '/session/edit/get', to: 'session#edit', as: 'session_edit'
    get '/session/logout', to: 'session#logout', as: 'session_logout'
    patch '/session/update/image', to: 'session#update_image', as: 'session_update_image'
    patch '/session/update/info', to: 'session#update_info', as: 'session_update_info'
    patch '/session/update/credintials', to: 'session#update_credintials', as: 'session_update_credintials'
    patch '/session/update/address', to: 'session#update_address', as: 'session_update_address'
    patch '/session/update/contact', to: 'session#update_contact', as: 'session_update_contact'

    get '/session/lending', to: 'session#borrowed', as: 'session_borrowed'
    get '/session/borrowing', to: 'session#borrowing', as: 'session_borrowing'
    get '/session/favourites', to: 'session#favourites', as: 'session_favourites'
    get '/session/likes', to: 'session#likes', as: 'session_likes'
    get '/session/followers', to: 'session#followers', as: 'session_followers'
    get '/session/following', to: 'session#following', as: 'session_following'
    get '/session/requests', to: 'session#requests', as: 'session_requests'
    get '/notifications/all', to: 'session#notifications_all', as: 'notifications_all'
    get '/notifications/items-requests', to:'session#notifications_item', as: 'notifications_item'
    get '/notifications/borrow', to: 'session#notifications_borrow', as: 'notifications_borrow'
    get '/notifications/reminder', to: 'session#notifications_reminder', as: 'notifications_reminder'

    get '/session/report/:ressource_id/get', to: 'session#report_new', as: 'report_new'
    post '/session/report/post', to: 'session#report_create', as: 'report_create'

 
  	resources :items do
        resources :comments
        resources :item_borrow_user do
            resources :borrow_messages
        end
    end

    post '/item/:item_id/comment/create', to: 'comments#create', as: 'create_item_comment'
    patch '/item/:item_id/comment/:id/update', to: 'comments#update', as: 'update_item_comment'
    delete '/item/:item_id/comment/:id/delete', to: 'comments#destroy', as: 'delete_item_comment'
    post '/items/:item_id/item_borrow_user/:item_borrow_user_id/borrow_messages/send', to: 'borrow_messages#create', as: 'send_message'

    post '/item/create', to: 'items#create', as: 'item_create'
    post '/item/:id/update', to:'items#update', as: 'item_update'

    get '/item/:username/enc-dt-:uuid-:id', to: 'items#show', as: 'item_show'
    get '/item/:username/enc-dt-:uuid-:id/ajax', to: 'items#show_ajax', as: 'item_show_ajax'
    get '/item/:username/enc-dt-:uuid-:id/edit', to: 'items#edit', as: 'item_edit'
    get '/item/:username/enc-dt-:uuid-:item_id/borrow', to: 'item_borrow_user#new', as: 'borrow_item'
    get '/item/:username/enc-dt-:uuid-:id/available', to: 'items#available', as: 'item_available'

    get '/item/:username/enc-dt-:uuid-:item_id/borrows', to: 'item_borrow_user#index', as: 'item_borrows'
    get '/item/enc-dt-:uuid-:item_id-:id/borrow', to: 'item_borrow_user#show', as: 'item_borrow'
    get '/item/enc-dt-:uuid-:item_id-:id/borrow/review', to: 'item_borrow_user#borrow_review', as: 'borrow_review'
    post '/item/enc-dt-:uuid-:item_id/borrow/create', to: 'item_borrow_user#create', as: 'create_item_borrow'
    get '/item/enc-dt-:uuid-:item_id-:id/borrow/description', to: 'item_borrow_user#description', as: 'item_borrow_description'
    get '/item/enc-dt-:uuid-:item_id-:id/borrow/description/download.pdf', to: 'item_borrow_user#download_borrow_data', as: 'item_borrow_description_download'

    get '/item/enc-dt-:uuid-:item_id-:id/borrow/extend', to: 'item_borrow_user#extend', as: 'item_borrow_extend'
    post '/item/enc-dt-:uuid-:item_id-:id/borrow/extend/post', to: 'item_borrow_user#extend_borrow', as: 'extend_borrow_post'
    get '/item/enc-dt-:uuid-:item_id-:id/borrow/extend/status/update', to: 'item_borrow_user#update_borrow_extension_status', as: 'update_borrow_extension_status'
    get '/item/enc-dt-:uuid-:item_id-:id/borrow/renew', to: 'item_borrow_user#extend', as: 'item_borrow_renew'
    post '/item/enc-dt-:uuid-:item_id-:id/borrow/renew/post', to: 'item_borrow_user#renew_borrow', as: 'renew_borrow_post'

    get '/items/enc-dt-:uuid-:item_id-:item_borrow_user_id/follow-ups', to: 'item_borrow_user#follow_ups', as: 'follow_ups'
    get '/items/:item_id/borrow/:item_borrow_user_id/follow-ups/sent', to: 'item_borrow_user#load_follow_ups_sent', as: 'load_follow_ups_sent'
    get '/items/:item_id/borrow/:item_borrow_user_id/follow-ups/received', to: 'item_borrow_user#load_follow_ups_received', as: 'load_follow_ups_received'
    post '/items/:item_id/borrow/:item_borrow_user_id/follow-ups/send', to: 'item_borrow_user#send_follow_up', as: 'send_follow_up'

    get '/items/enc-dt-:uuid-:item_id-:item_borrow_user_id/messages/admin', to: 'borrow_messages#admin_messages', as: 'admin_messages'
    get '/items/enc-dt-:uuid-:item_id-:item_borrow_user_id/messages/admin/load', to: 'borrow_messages#load_admin_messages', as: 'load_admin_messages'
    post '/items/:item_id/borrow_item_user/:item_borrow_user_id/borrow_messages/images/send', to: 'borrow_messages#send_images', as: 'message_send_images'
    post '/items/:item_id/borrow_item_user/:item_borrow_user_id/borrow_messages/admin/send', to: 'borrow_messages#send_admin_message', as: 'message_send_admin'

    get '/items/requests/all', to: 'item_requests#index', as: 'item_requests'
    get '/items/request/:username/enc-dt-:uuid-:id', to: 'item_requests#show', as: 'item_request'
    get '/items/request/:username/enc-dt-:uuid-:id/ajax', to: 'item_requests#show_ajax', as: 'item_request_ajax'
    post '/items/request/:id/like', to: 'item_requests#like', as: 'item_request_like'
    get '/item/requests/new', to: 'item_requests#new', as: 'new_item_request'
    post '/item/requests/create', to: 'item_requests#create', as: 'create_item_request'
    get '/item/request/:username/enc-dt-:uuid-:id/edit', to: 'item_requests#edit', as: 'edit_item_request'
    get '/item/request/:item_request_id/image/:id/delete', to: 'item_requests#delete_item_request_image', as: 'delete_item_request_image'
    patch '/item/request/:id/update', to: 'item_requests#update', as: 'update_item_request'
    get '/item/request/:id/status/update', to: 'item_requests#update_request_status', as: 'update_item_request_status'
    delete '/item/request/:id/destroy', to: 'item_requests#destroy', as: 'destroy_item_request'
    get '/item/request/:username/enc-dt-:uuid-:id/suggestions/new', to: 'item_requests#suggestion_new', as: 'item_request_new_suggestion'
    get '/item/request/:username/enc-dt-:uuid-:id/suggestions/exist', to: 'item_requests#suggestion_exist', as: 'item_request_exist_suggestion'
    post '/item/request/:id/suggestions/create', to: 'item_requests#suggestion_create', as: 'item_request_create_suggestion'
    post '/item/request/:id/suggestions/create/exist', to: 'item_requests#suggesion_create_exist', as: 'item_request_create_exist_suggestion'
    get '/item/request/:id/suggestions/all', to: 'item_requests#suggestion_all', as: 'item_request_suggestions'
    get '/item/request/:item_request_id/suggestion/:id/edit', to: 'item_requests#suggestion_edit', as: 'item_request_suggestion_edit'
    patch '/item/request/:item_request_id/suggestion/:id/update', to: 'item_requests#suggestion_update', as: 'item_request_suggestion_update'
    get '/item/request/:item_request_id/suggestion/:id/status/update', to: 'item_requests#suggestion_update_status', as: 'item_request_suggestion_update_status'

    get '/items/:item_id/item_borrow_user/:item_borrow_user_id/all', to: 'borrow_messages#borrow_all', as: 'borrow_messages_all'
    get '/items/:item_id/item_borrow_user/:id/update_status', to: 'item_borrow_user#update_status', as: 'update_status'
    post '/items/:item_id/item_borrow_user/:id/update', to: 'item_borrow_user#update', as: 'update_item_borrow_item_user'
    get '/items/:item_id/item_borrow_user/:id/delete', to: 'item_borrow_user#destroy', as: 'destroy_item_borrow_item_user'

    post '/comments/:id/delete', to: 'comments#destroy', as: 'delete_comment'
    get '/item/:item_id/image/:id/delete', to: 'items#delete_image_item', as: 'delete_item_image'

    post '/item/:id/like', to: 'items#like_item', as: 'like'
    get '/item/:item_id/like/:id/destroy', to: 'items#like_item_destroy', as: 'like_destroy'
    post '/item/:id/favourite', to: 'items#favourite_item', as: 'favourite'
    get '/item/:item_id/favourite/:id/destroy', to: 'items#favourite_item_destroy', as: 'favourite_destroy'

    get '/users/all', to: 'user#index', as: 'users'

    resources :user

    get '/user/:username-:id/items', to: 'user#show', as: 'user_items'
    get '/user/:username-:id/likes', to: 'user#likes', as: 'user_likes'
    get '/user/:username-:id/followers', to: 'user#followers', as: 'user_followers'
    get '/user/:username-:id/following', to: 'user#following', as: 'user_following'
    get '/user/:username-:id/lending', to: 'user#borrowed', as: 'user_borrows'

app/helpers/session_helper.rb
module SessionHelper
	include UserHelper
end

app/views/session/borrowing.html.erb
<section class="yb-header-else">
	<div class="yb-header-else-container">
		<div class="yb-header-user">
			<div class="yb-header-image">
				<% if session_user.image? %>
					<%= image_tag session_user.image.url %>
				<% else %>
					<img src="/assets/default.jpg"/>
				<% end %>
			</div>
			<h4><%= session_user.username %></h4>
		</div>
		<div class="yb-session-menu">
			<ul>
				<li><%= link_to "Items", session_items_path %></li>
				<li><%= link_to "Likes", session_likes_path %></li>
				<li><%= link_to "Followers", session_followers_path %></li>
				<li><%= link_to "Following", session_following_path %></li>
				<li class="active"><%= link_to "Item Data", session_borrowed_path %></li>
			</ul>
		</div>
	</div>
</section>
<section class="yb-session-main">
	<div class="yb-session-info-about">
		<%= render "partials/session" %>
	</div>
	<div class="yb-session-container">
		<div class="yb-session-menu">
			<ul>
				<li><%= link_to "Items", session_items_path %></li>
				<li><%= link_to "Likes", session_likes_path %></li>
				<li><%= link_to "Followers", session_followers_path %></li>
				<li><%= link_to "Following", session_following_path %></li>
				<li class="active"><%= link_to "Item Data", session_borrowed_path %></li>
			</ul>
		</div>
		<div class="yb-session-data">
			<% if @borrows.count > 0 %>
				<div class="yb-borrow-items">
					<% @borrows.each do |borrow| %>
						<div class="yb-borrow-item-single">
							<div class="yb-borrow-status">
								<div class="yb-status" id="yb-show-menu-<%= borrow.id %>" data-id="<%= borrow.id %>" style="background: <%= borrow.check_expiration %>"></div>
								<div class="yb-borrow-menu yb-menu-list" id="yb-menu-items-<%= borrow.id %>">
									<ul>
										<% if borrow.check_expiration == "orange" %>
											<% if session_user.id == borrow.user.id %>
												<li><a id="yb-edit-borrow-item-<%= borrow.id %>" href="<%= edit_item_item_borrow_user_path(borrow.item, borrow) %>"><span class="item-icon"><i class="icon ion-edit"></i></span><span class="item-text">Update</span></a></li>
											<% elsif session_user.id == borrow.item.user.id %>
												<li><a href="<%= update_status_path(borrow.item, borrow) %>?status=2" class="yb-update-borrow-status-link" data-status="rejected" data-borrow="<%= borrow.id %>" data-item="<%= borrow.item.id %>" data-url="<%= item_item_borrow_user_borrow_messages_path(borrow.item, borrow) %>" data-receiver="<% if session_user.id == borrow.user.id %><%= borrow.item.user.id %><% else %><%= borrow.user.id %><% end %>" data-sender="<%= session_user.username %>" data-path="<%= item_borrow_path(borrow.uuid, borrow.item, borrow) %>"><span class="item-icon"><i class="icon ion-close-round"></i></span><span class="item-text">Reject</span></a></li>
											<% end %>
										<% elsif borrow.check_expiration == "lightgreen" %>
											<% if session_user.id == borrow.last_update_user_id %>
												<li><a id="yb-edit-borrow-item-<%= borrow.id %>" href="<%= edit_item_item_borrow_user_path(borrow.item, borrow) %>"><span class="item-icon"><i class="icon ion-edit"></i></span><span class="item-text">Update</span></a></li>
											<% else %>
												<li><a href="<%= update_status_path(borrow.item, borrow) %>?status=1" class="yb-update-borrow-status-link" data-status="accepted" data-borrow="<%= borrow.id %>" data-item="<%= borrow.item.id %>" data-url="<%= item_item_borrow_user_borrow_messages_path(borrow.item, borrow) %>" data-receiver="<% if session_user.id == borrow.user.id %><%= borrow.item.user.id %><% else %><%= borrow.user.id %><% end %>" data-sender="<%= session_user.username %>" data-path="<%= item_borrow_path(borrow.uuid, borrow.item, borrow) %>"><span class="item-icon"><i class="icon ion-checkmark-round"></i></span><span class="item-text">Accept</span></a></li>
												<li><a href="<%= update_status_path(borrow.item, borrow) %>?status=2" class="yb-update-borrow-status-link" data-status="rejected" data-borrow="<%= borrow.id %>" data-item="<%= borrow.item.id %>" data-url="<%= item_item_borrow_user_borrow_messages_path(borrow.item, borrow) %>" data-receiver="<% if session_user.id == borrow.user.id %><%= borrow.item.user.id %><% else %><%= borrow.user.id %><% end %>" data-sender="<%= session_user.username %>" data-path="<%= item_borrow_path(borrow.uuid, borrow.item, borrow) %>"><span class="item-icon"><i class="icon ion-close-round"></i></span><span class="item-text">Reject</span></a></li>
												<li><a id="yb-edit-borrow-item-<%= borrow.id %>" href="<%= edit_item_item_borrow_user_path(borrow.item, borrow) %>"><span class="item-icon"><i class="icon ion-edit"></i></span><span class="item-text">Update</span></a></li>
											<% end %>
										<% elsif borrow.check_expiration == "green" %>
											<% if session_user.id == borrow.user.id %>
												<% if borrow.was_rendered %>
												<li><a href="<%= item_borrow_extend_path(borrow.uuid, borrow.item, borrow) %>" id="yb-open-borrow-extend-<%= borrow.id %>"><span class="item-icon"><i class="icon ion-arrow-expand"></i></span><span class="item-text">Extend</span></a></li>
												<% end %>
												<% if Array["returned", "succeeded"].include?(borrow.status) %>
												<li><a href="<%= item_borrow_renew_path(borrow.uuid, borrow.item, borrow) %>" id="yb-open-borrow-renew-<%= borrow.id %>"><span class="item-icon"><i class="icon ion-refresh"></i></span><span class="item-text">Renew</span></a></li>
												<% end %>
												<li><a href="<%= report_new_path(borrow.id) %>?ressource=borrow" id="yb-get-report-<%= borrow.id %>"><span class="item-icon"><i class="icon ion-information-circled"></i></span><span class="item-text">Report</span></a></li>
											<% elsif session_user.id == borrow.item.user.id %>
												<% if borrow.was_received and !borrow.item.user.is_private? %>
												<li><a href="<%= follow_ups_path(borrow.uuid, borrow.item, borrow) %>" id="yb-open-follow-ups-<%= borrow.id %>"><span class="item-icon"><i class="icon ion-arrow-return-right"></i></span><span class="item-text">Follow Up</span></a></li>
												<% end %>
												<li><a href="<%= report_new_path(borrow.id) %>?ressource=borrow" id="yb-get-report-<%= borrow.id %>"><span class="item-icon"><i class="icon ion-information-circled"></i></span><span class="item-text">Report</span></a></li>
											<% end %>
										<% elsif borrow.check_expiration == "red" %>
											<% if session_user.id == borrow.user.id %>
												<li><a href="<%= destroy_item_borrow_item_user_path(borrow.item, borrow) %>?method=delete"><span class="item-icon"><i class="icon ion-trash-b"></i></span><span class="item-text">Delete</span></a></li>
												<li><a href="<%= item_borrow_renew_path(borrow.uuid, borrow.item, borrow) %>" id="yb-open-borrow-renew-<%= borrow.id %>"><span class="item-icon"><i class="icon ion-refresh"></i></span><span class="item-text">Renew</span></a></li>
												<li><a href="<%= report_new_path(borrow.id) %>?ressource=borrow" id="yb-get-report-<%= borrow.id %>"><span class="item-icon"><i class="icon ion-information-circled"></i></span><span class="item-text">Report</span></a></li>
											<% elsif session_user.id == borrow.item.user.id %>
												<li><a href="<%= destroy_item_borrow_item_user_path(borrow.item, borrow) %>?method=delete"><span class="item-icon"><i class="icon ion-trash-b"></i></span><span class="item-text">Delete</span></a></li>
												<li><a href="<%= report_new_path(borrow.id) %>?ressource=borrow" id="yb-get-report-<%= borrow.id %>"><span class="item-icon"><i class="icon ion-information-circled"></i></span><span class="item-text">Report</span></a></li>
											<% end %>
										<% end %>
									</ul>
								</div>
							</div>
							<div class="yb-image">
								<%= image_tag borrow.item.item_image[0].image.url, alt: borrow.item.name %>
							</div>
							<div class="yb-about">
								<h3 style="margin-top: 0px;"><%= link_to borrow.item.name, item_borrow_path(borrow.item.uuid, borrow.item, borrow) %></h3>
									<p class="yb-category">by <%= link_to borrow.item.user.name, user_items_path(borrow.item.user.username, borrow.item.user) %></p>
								<p class="yb-item-data">
									<span class="yb-data">From - <%= borrow.from_date.localtime.strftime("%a %d %b, %Y at %H:%M") %></span>
									<span class="yb-data">To - <%= borrow.to_date.localtime.strftime("%a %d %b, %Y at %H:%M") %></span>
								</p>
							</div>
							<script type="text/javascript">$("#yb-show-menu-<%= borrow.id %>").showMenu();$("#yb-edit-borrow-item-<%= borrow.id %>, #yb-get-report-<%= borrow.id %>, #yb-open-follow-ups-<%= borrow.id %>, #yb-open-borrow-extend-<%= borrow.id %>, #yb-open-borrow-extend-<%= borrow.id %>").magnificPopup({type: 'ajax'});</script>
						</div>
					<% end %>
				</div>
			<% else %>
				<p class="yb-error">NO BORROWING ITEM</p>
			<% end %>
		</div>
	</div>
</section>

app/views/session/favourites.html.erb
<section class="yb-header-else">
	<div class="yb-header-else-container">
		<div class="yb-header-user">
			<div class="yb-header-image">
				<% if session_user.image? %>
					<%= image_tag session_user.image.url %>
				<% else %>
					<img src="/assets/default.jpg"/>
				<% end %>
			</div>
			<h4><%= session_user.username %></h4>
		</div>
		<div class="yb-session-menu">
			<ul>
				<li><%= link_to "Items", session_items_path %></li>
				<li><%= link_to "Likes", session_likes_path %></li>
				<li><%= link_to "Followers", session_followers_path %></li>
				<li><%= link_to "Following", session_following_path %></li>
				<li class="active"><%= link_to "Item Data", session_borrowed_path %></li>
			</ul>
		</div>
	</div>
</section>
<section class="yb-session-main">
	<div class="yb-session-info-about">
		<%= render "partials/session" %>
	</div>
	<div class="yb-session-container">
		<div class="yb-session-menu">
			<ul>
				<li><%= link_to "Items", session_items_path %></li>
				<li><%= link_to "Likes", session_likes_path %></li>
				<li><%= link_to "Followers", session_followers_path %></li>
				<li><%= link_to "Following", session_following_path %></li>
				<li class="active"><%= link_to "Item Data", session_borrowed_path %></li>
			</ul>
		</div>
		<div class="yb-session-data">
			<% if @favourites.count > 0 %>
				<div class="yb-borrow-items">
					<% @favourites.each do |item| %>
						<div class="yb-borrow-item-single" id="item-favourite-<%= item.id %>">
							<div class="yb-borrow-status">
								<div class="yb-status" data-url="<%= favourite_destroy_path(item.item, item) %>" data-id="<%= item.id %>" id="yb-favourite-remove-<%= item.id %>" style="background: red"></div>
							</div>
							<div class="yb-image">
								<%= image_tag item.item.item_image[0].image.url, alt: item.item.name %>
							</div>
							<div class="yb-about">
								<h3><%= link_to item.item.name, item_show_path(item.item.user.username, item.item.uuid, item.item) %></h3>
								<p class="yb-category">
									<a href="<%= category_path(item.item.category.uuid, item.item.category) %>"><%= item.item.category.name %></a> - 
									<a href="<%= subcategory_path(item.item.category.uuid, item.item.category, item.item.subcategory) %>"><%= item.item.subcategory.name %></a>
								</p>
								<p class="yb-item-data" style="margin-top: -8px;">
									<span>by <%= link_to item.item.user.name, user_path(item.item.user) %></span> - 
									<span id="fav-item-date-<%= item.id %>" data-date="<%= item.item.created_at.strftime("%Y-%m-%d %H:%M:%S") %>"></span>
								</p>
							</div>
							<script type="text/javascript">$("#fav-item-date-<%= item.id %>").setDate();$("#yb-favourite-remove-<%= item.id %>").removeFavourite();</script>
						</div>
					<% end %>
				</div>
			<% else %>
				<p class="yb-error">NO FAVOURITE ITEMS</p>
			<% end %>
		</div>
	</div>
</section>

app/views/session/index.html.erb
<section class="yb-header-else">
	<div class="yb-header-else-container">
		<div class="yb-header-user">
			<div class="yb-header-image">
				<% if session_user.image? %>
					<%= image_tag session_user.image.url %>
				<% else %>
					<img src="/assets/default.jpg"/>
				<% end %>
			</div>
			<h4><%= session_user.username %></h4>
		</div>
		<div class="yb-session-menu">
			<ul>
				<li class="active"><a href="<%= session_items_path %>">Items</a></li>
				<li><a href="<%= session_likes_path %>">Likes</a></li>
				<li><a href="<%= session_followers_path %>">Followers</a></li>
				<li><a href="<%= session_following_path %>">Following</a></li>
				<li><a href="<%= session_borrowed_path %>">Item Data</a></li>
			</ul>
		</div>
	</div>
</section>
<section class="yb-session-main">
	<div class="yb-session-info-about">
		<%= render "partials/session" %>
	</div>
	<div class="yb-session-container">
		<div class="yb-session-menu">
			<ul>
				<li class="active"><a href="<%= session_items_path %>">Items</a></li>
				<li><a href="<%= session_likes_path %>">Likes</a></li>
				<li><a href="<%= session_followers_path %>">Followers</a></li>
				<li><a href="<%= session_following_path %>">Following</a></li>
				<li><a href="<%= session_borrowed_path %>">Item Data</a></li>
			</ul>
		</div>
		<div class="yb-session-data">
			<% if @items.count > 0 %>
				<div class="yb-user-items">
					<div id="yb-item-list">
						<%= render @items %>
					</div>
		        </div>
		        <%= will_paginate @items %>
		        <div class="yb-items-loader">
				   	<%= image_tag '/assets/loading.gif', alt: 'Loading' %>
				</div>
			<% else %>
                <p class="yb-error">NO POSTED ITEM</p>
            <% end %>
		</div>
	</div>
</section>

app/views/session/likes.html.erb
<section class="yb-header-else">
	<div class="yb-header-else-container">
		<div class="yb-header-user">
			<div class="yb-header-image">
				<% if session_user.image? %>
					<%= image_tag session_user.image.url %>
				<% else %>
					<img src="/assets/default.jpg"/>
				<% end %>
			</div>
			<h4><%= session_user.username %></h4>
		</div>
		<div class="yb-session-menu">
			<ul>
				<li><%= link_to "Items", session_items_path %></li>
				<li class="active"><%= link_to "Likes", session_likes_path %></li>
				<li><%= link_to "Followers", session_followers_path %></li>
				<li><%= link_to "Following", session_following_path %></li>
				<li><%= link_to "Item Data", session_borrowed_path %></li>
			</ul>
		</div>
	</div>
</section>
<section class="yb-session-main">
	<div class="yb-session-info-about">
		<%= render "partials/session" %>
	</div>
	<div class="yb-session-container">
		<div class="yb-session-menu">
			<ul>
				<li><%= link_to "Items", session_items_path %></li>
				<li class="active"><%= link_to "Likes", session_likes_path %></li>
				<li><%= link_to "Followers", session_followers_path %></li>
				<li><%= link_to "Following", session_following_path %></li>
				<li><%= link_to "Item Data", session_borrowed_path %></li>
			</ul>
		</div>
		<div class="yb-session-data">
			<% if @likes.count > 0 %>
				<div class="yb-borrow-items">
					<% @likes.each do |item| %>
						<div class="yb-borrow-item-single" id="item-like-<%= item.id %>">
							<div class="yb-borrow-status">
								<div class="yb-status" data-url="<%= like_destroy_path(item.item, item) %>" data-id="<%= item.id %>" id="yb-like-remove-<%= item.id %>" style="background: red"></div>
							</div>
							<div class="yb-image">
								<%= image_tag item.item.item_image[0].image.url, alt: item.item.name %>
							</div>
							<div class="yb-about">
								<h3><%= link_to item.item.name, item_show_path(item.item.user.username, item.item.uuid, item.item) %></h3>
								<p class="yb-category">
									<a href="<%= category_path(item.item.category.uuid, item.item.category) %>"><%= item.item.category.name %></a> - 
									<a href="<%= subcategory_path(item.item.category.uuid, item.item.category, item.item.subcategory) %>"><%= item.item.subcategory.name %></a>
								</p>
								<p class="yb-item-data" style="margin-top: -8px;">
									<span>by <%= link_to item.item.user.name, user_path(item.item.user) %></span> - 
									<span id="like-item-date-<%= item.id %>" data-date="<%= item.item.created_at.strftime("%Y-%m-%d %H:%M:%S") %>"></span>
								</p>
							</div>
							<script type="text/javascript">$("#like-item-date-<%= item.id %>").setDate();$("#yb-like-remove-<%= item.id %>").removeLike();</script>
						</div>
					<% end %>
				</div>
			<% else %>
				<p class="yb-error">NO LIKED ITEMS</p>
			<% end %>
		</div>
	</div>
</section>