config/routes.rb
Rails.application.routes.draw do

    require 'sidekiq/web'
    require 'sidekiq/cron/web'

    mount Sidekiq::Web => '/admin/sidekiq/report'

    get '/404', to: 'error#not_found_error', as: 'not_found_error', via: :all
    get '/500', to: 'error#internal_server_error', as: 'internal_server_error', via: :all

    root 'home#index'
    get 'home/index'
    get 'search/all', to:'home#search', as: 'search'
    get 'search/items', to: 'home#search_items', as: 'search_items'
    get 'search/requests', to: 'home#search_requests', as: 'search_requests'
    get 'search/users', to: 'home#search_users', as: 'search_users'
    post 'notification/send', to: 'home#notification_getway', as: 'notification_getway'

    get '/session', to: 'session#index', as: 'session'
    get '/session/profile', to: 'session#index', as: 'session_profile'
    get '/session/items', to: 'session#index', as: 'session_items'
    get '/session/edit/get', to: 'session#edit', as: 'session_edit'
    get '/session/logout', to: 'session#logout', as: 'session_logout'
    patch '/session/update/image', to: 'session#update_image', as: 'session_update_image'
    patch '/session/update/info', to: 'session#update_info', as: 'session_update_info'
    patch '/session/update/credintials', to: 'session#update_credintials', as: 'session_update_credintials'
    patch '/session/update/address', to: 'session#update_address', as: 'session_update_address'
    patch '/session/update/contact', to: 'session#update_contact', as: 'session_update_contact'

    get '/session/lending', to: 'session#borrowed', as: 'session_borrowed'
    get '/session/borrowing', to: 'session#borrowing', as: 'session_borrowing'
    get '/session/favourites', to: 'session#favourites', as: 'session_favourites'
    get '/session/likes', to: 'session#likes', as: 'session_likes'
    get '/session/followers', to: 'session#followers', as: 'session_followers'
    get '/session/following', to: 'session#following', as: 'session_following'
    get '/session/requests', to: 'session#requests', as: 'session_requests'
    get '/notifications/all', to: 'session#notifications_all', as: 'notifications_all'
    get '/notifications/items-requests', to:'session#notifications_item', as: 'notifications_item'
    get '/notifications/borrow', to: 'session#notifications_borrow', as: 'notifications_borrow'
    get '/notifications/reminder', to: 'session#notifications_reminder', as: 'notifications_reminder'

    get '/session/report/:ressource_id/get', to: 'session#report_new', as: 'report_new'
    post '/session/report/post', to: 'session#report_create', as: 'report_create'

 
  	resources :items do
        resources :comments
        resources :item_borrow_user do
            resources :borrow_messages
        end
    end

    post '/item/:item_id/comment/create', to: 'comments#create', as: 'create_item_comment'
    patch '/item/:item_id/comment/:id/update', to: 'comments#update', as: 'update_item_comment'
    delete '/item/:item_id/comment/:id/delete', to: 'comments#destroy', as: 'delete_item_comment'
    post '/items/:item_id/item_borrow_user/:item_borrow_user_id/borrow_messages/send', to: 'borrow_messages#create', as: 'send_message'

    post '/item/create', to: 'items#create', as: 'item_create'
    post '/item/:id/update', to:'items#update', as: 'item_update'

    get '/item/:username/enc-dt-:uuid-:id', to: 'items#show', as: 'item_show'
    get '/item/:username/enc-dt-:uuid-:id/ajax', to: 'items#show_ajax', as: 'item_show_ajax'
    get '/item/:username/enc-dt-:uuid-:id/edit', to: 'items#edit', as: 'item_edit'
    get '/item/:username/enc-dt-:uuid-:item_id/borrow', to: 'item_borrow_user#new', as: 'borrow_item'
    get '/item/:username/enc-dt-:uuid-:id/available', to: 'items#available', as: 'item_available'

    get '/item/:username/enc-dt-:uuid-:item_id/borrows', to: 'item_borrow_user#index', as: 'item_borrows'
    get '/item/enc-dt-:uuid-:item_id-:id/borrow', to: 'item_borrow_user#show', as: 'item_borrow'
    get '/item/enc-dt-:uuid-:item_id-:id/borrow/review', to: 'item_borrow_user#borrow_review', as: 'borrow_review'
    post '/item/enc-dt-:uuid-:item_id/borrow/create', to: 'item_borrow_user#create', as: 'create_item_borrow'
    get '/item/enc-dt-:uuid-:item_id-:id/borrow/description', to: 'item_borrow_user#description', as: 'item_borrow_description'
    get '/item/enc-dt-:uuid-:item_id-:id/borrow/description/download.pdf', to: 'item_borrow_user#download_borrow_data', as: 'item_borrow_description_download'

    get '/item/enc-dt-:uuid-:item_id-:id/borrow/extend', to: 'item_borrow_user#extend', as: 'item_borrow_extend'
    post '/item/enc-dt-:uuid-:item_id-:id/borrow/extend/post', to: 'item_borrow_user#extend_borrow', as: 'extend_borrow_post'
    get '/item/enc-dt-:uuid-:item_id-:id/borrow/extend/status/update', to: 'item_borrow_user#update_borrow_extension_status', as: 'update_borrow_extension_status'
    get '/item/enc-dt-:uuid-:item_id-:id/borrow/renew', to: 'item_borrow_user#extend', as: 'item_borrow_renew'
    post '/item/enc-dt-:uuid-:item_id-:id/borrow/renew/post', to: 'item_borrow_user#renew_borrow', as: 'renew_borrow_post'

    get '/items/enc-dt-:uuid-:item_id-:item_borrow_user_id/follow-ups', to: 'item_borrow_user#follow_ups', as: 'follow_ups'
    get '/items/:item_id/borrow/:item_borrow_user_id/follow-ups/sent', to: 'item_borrow_user#load_follow_ups_sent', as: 'load_follow_ups_sent'
    get '/items/:item_id/borrow/:item_borrow_user_id/follow-ups/received', to: 'item_borrow_user#load_follow_ups_received', as: 'load_follow_ups_received'
    post '/items/:item_id/borrow/:item_borrow_user_id/follow-ups/send', to: 'item_borrow_user#send_follow_up', as: 'send_follow_up'

    get '/items/enc-dt-:uuid-:item_id-:item_borrow_user_id/messages/admin', to: 'borrow_messages#admin_messages', as: 'admin_messages'
    get '/items/enc-dt-:uuid-:item_id-:item_borrow_user_id/messages/admin/load', to: 'borrow_messages#load_admin_messages', as: 'load_admin_messages'
    post '/items/:item_id/borrow_item_user/:item_borrow_user_id/borrow_messages/images/send', to: 'borrow_messages#send_images', as: 'message_send_images'
    post '/items/:item_id/borrow_item_user/:item_borrow_user_id/borrow_messages/admin/send', to: 'borrow_messages#send_admin_message', as: 'message_send_admin'

    get '/items/requests/all', to: 'item_requests#index', as: 'item_requests'
    get '/items/request/:username/enc-dt-:uuid-:id', to: 'item_requests#show', as: 'item_request'
    get '/items/request/:username/enc-dt-:uuid-:id/ajax', to: 'item_requests#show_ajax', as: 'item_request_ajax'
    post '/items/request/:id/like', to: 'item_requests#like', as: 'item_request_like'
    get '/item/requests/new', to: 'item_requests#new', as: 'new_item_request'
    post '/item/requests/create', to: 'item_requests#create', as: 'create_item_request'
    get '/item/request/:username/enc-dt-:uuid-:id/edit', to: 'item_requests#edit', as: 'edit_item_request'
    get '/item/request/:item_request_id/image/:id/delete', to: 'item_requests#delete_item_request_image', as: 'delete_item_request_image'
    patch '/item/request/:id/update', to: 'item_requests#update', as: 'update_item_request'
    get '/item/request/:id/status/update', to: 'item_requests#update_request_status', as: 'update_item_request_status'
    delete '/item/request/:id/destroy', to: 'item_requests#destroy', as: 'destroy_item_request'
    get '/item/request/:username/enc-dt-:uuid-:id/suggestions/new', to: 'item_requests#suggestion_new', as: 'item_request_new_suggestion'
    get '/item/request/:username/enc-dt-:uuid-:id/suggestions/exist', to: 'item_requests#suggestion_exist', as: 'item_request_exist_suggestion'
    post '/item/request/:id/suggestions/create', to: 'item_requests#suggestion_create', as: 'item_request_create_suggestion'
    post '/item/request/:id/suggestions/create/exist', to: 'item_requests#suggesion_create_exist', as: 'item_request_create_exist_suggestion'
    get '/item/request/:id/suggestions/all', to: 'item_requests#suggestion_all', as: 'item_request_suggestions'
    get '/item/request/:item_request_id/suggestion/:id/edit', to: 'item_requests#suggestion_edit', as: 'item_request_suggestion_edit'
    patch '/item/request/:item_request_id/suggestion/:id/update', to: 'item_requests#suggestion_update', as: 'item_request_suggestion_update'
    get '/item/request/:item_request_id/suggestion/:id/status/update', to: 'item_requests#suggestion_update_status', as: 'item_request_suggestion_update_status'

    get '/items/:item_id/item_borrow_user/:item_borrow_user_id/all', to: 'borrow_messages#borrow_all', as: 'borrow_messages_all'
    get '/items/:item_id/item_borrow_user/:id/update_status', to: 'item_borrow_user#update_status', as: 'update_status'
    post '/items/:item_id/item_borrow_user/:id/update', to: 'item_borrow_user#update', as: 'update_item_borrow_item_user'
    get '/items/:item_id/item_borrow_user/:id/delete', to: 'item_borrow_user#destroy', as: 'destroy_item_borrow_item_user'

    post '/comments/:id/delete', to: 'comments#destroy', as: 'delete_comment'
    get '/item/:item_id/image/:id/delete', to: 'items#delete_image_item', as: 'delete_item_image'

    post '/item/:id/like', to: 'items#like_item', as: 'like'
    get '/item/:item_id/like/:id/destroy', to: 'items#like_item_destroy', as: 'like_destroy'
    post '/item/:id/favourite', to: 'items#favourite_item', as: 'favourite'
    get '/item/:item_id/favourite/:id/destroy', to: 'items#favourite_item_destroy', as: 'favourite_destroy'

    get '/users/all', to: 'user#index', as: 'users'

    resources :user

    get '/user/:username-:id/items', to: 'user#show', as: 'user_items'
    get '/user/:username-:id/likes', to: 'user#likes', as: 'user_likes'
    get '/user/:username-:id/followers', to: 'user#followers', as: 'user_followers'
    get '/user/:username-:id/following', to: 'user#following', as: 'user_following'
    get '/user/:username-:id/lending', to: 'user#borrowed', as: 'user_borrows'

app/views/partials/_adminh.html.erb
<script type="text/javascript">
	<% flash.each do |key, value| %>
		if("<%= key %>" == "notice" || "<%= key %>" == "success"){
			showSuccessMessage("<%= key %>","<%= value %>");
		} else {
			showErrorMessage("<%= key %>","<%= value %>");
		}
	<% end -%>
</script>
<% if is_admin_logged_in? %>
<input type="hidden" id="session_admin_id" value="admin_<%= session_admin.id %>">
<input type="hidden" id="session_admin_name" value="<%= session_admin.username %>">
<% end -%>
<section class="yb-header">
	<div class="yb-header-container">
		<h2><a href="<%= admin_home_path %>">Admin - Yo Buddy !</a></h2>
		<div class="yb-header-right">
			<% if is_admin_logged_in? %>
				<div class="yb-header-sign-in">
					<p><%= link_to "ADMINS", admin_admins_path %></p>
				</div>
				<div class="yb-header-sign-in">
					<p><%= link_to "CATEGORIES", admin_categories_path %></p>
				</div>
				<div class="yb-header-sign-in">
					<p><%= link_to "ITEMS", admin_items_path %></p>
				</div>
				<div class="yb-header-sign-in">
					<p><%= link_to "BORROWS", admin_borrows_all_path %></p>
				</div>
				<div class="yb-header-sign-in">
					<p><%= link_to "REPORTS", "#" %></p>
				</div>
				<div class="yb-header-sign-in">
					<p><%= link_to "SETTINGS", "#" %></p>
				</div>
				<div class="yb-header-signed-in">
					<a href="#">
						<%= image_tag session_admin.image.url, alt: session_admin.username %>
					</a>
				</div>
			<% end %>
			<div class="yb-header-menu">
				<span><i class="icon ion-ios-search"></i></span>
			</div>
		</div>
	</div>
</section>

app/views/partials/_adminu.html.erb
<script type="text/javascript">
	<% flash.each do |key, value| %>
		if("<%= key %>" == "notice" || "<%= key %>" == "success"){
			showSuccessMessage("<%= key %>","<%= value %>");
		} else {
			showErrorMessage("<%= key %>","<%= value %>");
		}
	<% end -%>
</script>
<% if is_admin_user_logged_in? %>
<%= hidden_field_tag(:session_user_id, session_admin_user.user.id) %>
<%= hidden_field_tag(:session_username, session_admin_user.user.username) %>
<%= hidden_field_tag(:session_name, session_admin_user.user.name) %>
<% end -%>
<section class="yb-header">
	<div class="yb-header-container">
		<h2><a href="<%= admin_u_path %>">Admin - User - Yo Buddy !</a></h2>
		<div class="yb-header-right">
			<% if is_admin_user_logged_in? %>
				<div class="yb-header-sign-in">
					<p><%= link_to "USERS", "#" %></p>
				</div>
				<div class="yb-header-sign-in">
					<p><%= link_to "ITEMS", admin_u_items_path %></p>
				</div>
				<div class="yb-header-sign-in">
					<p><%= link_to "BORROWS", admin_u_borrows_path %></p>
				</div>
				<div class="yb-header-sign-in">
					<p><%= link_to "REPORTS", "#" %></p>
				</div>
				<div class="yb-header-sign-in">
					<p><%= link_to "ACTIVATION", admin_u_activation_path %></p>
				</div>
				<div class="yb-header-signed-in">
					<a href="#">
						<%= image_tag "/assets/default.jpg", alt: session_admin_user.user.username %>
					</a>
				</div>
				<div class="yb-header-menu">
					<span><i class="icon ion-ios-bell-outline"></i></span>
					<span id="yb-session-notifications" class="yb-header-tag" <% if session_admin_user.user.notification_count <= 0 %> style="display: none;" <% end -%> ><%= session_admin_user.user.notification_count %></span>
				</div>
			<% end %>
			<div class="yb-header-menu">
				<span><i class="icon ion-ios-search"></i></span>
			</div>
		</div>
	</div>
</section>

app/views/partials/_footer.html.erb
<section class="yb-footer">
	
</section>

app/views/partials/_header.html.erb
<script type="text/javascript">
	<% flash.each do |key, value| %>
		if("<%= key %>" == "notice" || "<%= key %>" == "success"){
			showSuccessMessage("<%= key %>","<%= value %>");
		} else if("<%= key %>" == "info"){
			showInfoMessage("<%= key %>", "<%= value %>");
		} else {
			showErrorMessage("<%= key %>","<%= value %>");
		}
	<% end -%>
</script>
<% if is_logged_in? %>
<%= hidden_field_tag(:session_user_id, session_user.id) %>
<%= hidden_field_tag(:session_username, session_user.username) %>
<%= hidden_field_tag(:session_name, session_user.name) %>
<% end -%>
<section class="yb-header">
	<div class="yb-header-container">
		<h2><a href="/">Yo Buddy !</a></h2>
		<div class="yb-header-right">
			<div class="yb-header-sign-in">
				<p><%= link_to "CATEGORIES", category_index_path %></p>
			</div>
			<div class="yb-header-sign-in">
				<p><%= link_to "ITEMS", items_path %></p>
			</div>
			<div class="yb-header-sign-in">
				<p><%= link_to "REQUESTS", item_requests_path %></p>
			</div>
			<% if is_logged_in? %>
				<div class="yb-header-signed-in">
					<a href="#" id="yb-show-session-menu" data-id="session">
						<% if session_user.image? %>
							<%= image_tag session_user.image.url, title: session_user.username %>
						<% else %>
							<img src="/assets/default.jpg" alt="Profile Image" title="<%= session_user.username %>" />
						<% end %>
					</a>
					<div class="yb-menu-list" style="display:none; margin-left: -95px; margin-top: 5px;" id="yb-menu-items-session">
						<ul>
							<li><a href="/session/items"><span class="item-icon"><i class="icon ion-ios-cart"></i></span><span class="item-text">Items</span></a></li>
							<li><a href="/session/requests"><span class="item-icon"><i class="icon ion-forward"></i></span><span class="item-text">Requests</span></a></li>
							<hr style="width: 100%" />
							<li><a href="/session/lending"><span class="item-icon"><i class="icon ion-ios-arrow-thin-right"></i></span><span class="item-text">Lending</span></a></li>
							<li><a href="/session/borrowing"><span class="item-icon"><i class="icon ion-ios-arrow-thin-left"></i></span><span class="item-text">Borrowing</span></a></li>
							<hr style="width: 100%"/>
							<li><a href="/session/likes"><span class="item-icon"><i class="icon ion-ios-heart-outline"></i></span><span class="item-text">Likes</span></a></li>
							<li><a href="/session/favourites"><span class="item-icon"><i class="icon ion-ios-star-outline"></i></span><span class="item-text">Favourites</span></a></li>
							<hr style="width: 100%"/>
							<li><a href="/session/followers"><span class="item-icon"><i class="icon ion-ios-arrow-thin-right"></i></span><span class="item-text">Followers</span></a></li>
							<li><a href="/session/following"><span class="item-icon"><i class="icon ion-ios-arrow-thin-left"></i></span><span class="item-text">Following</span></a></li>
							<hr style="width: 100%"/>
							<li><a href="/session/logout"><span class="item-icon"><i class="icon ion-log-out"></i></span><span class="item-text">Log Out</span></a></li>
							<% if session_user.is_private? %>
								<li><a href="<%= admin_u_path %>"><span class="item-icon"><i class="icon ion-log-in"></i></span><span class="item-text">Admin User</span></a></li>
							<% end %>
						</ul>
					</div>
				</div>
				<div class="yb-header-menu">
					<a href="<%= notifications_all_path %>">
						<span><i class="icon ion-ios-bell-outline"></i></span>
					</a>
					<span id="yb-session-notifications-<%= session_user.id %>" class="yb-header-tag yb-session-notifications-<%= session_user.id %>" <% if session_user.notification_count <= 0 %> style="display: none;" <% end -%> ><%= session_user.notification_count %></span>
				</div>
			<% else %>
				<div class="yb-header-sign-in">
					<p><a href="/user/new">SIGN IN</a></p>
				</div>
			<% end %>
			<div class="yb-header-menu" id="yb-seach-toggle">
				<span><i class="icon ion-ios-search"></i></span>
			</div>
		</div>
		<div class="yb-header-right-else">
			<div class="yb-header-menu" id="yb-sidebar-toggle">
				<span><i class="icon ion-android-menu"></i></span>
			</div>
		</div>
	</div>
</section>

app/views/partials/_search.html.erb
<section class="yb-search-overlay" id="yb-search-overlay"></section>
<section class="yb-search-container" id="yb-search-container">
	<div class="yb-search-form">
		<div class="yb-search-form-content">
			<form method="get" action="<%= search_path %>" id="yb-live-search">
				<div class="yb-search-form-icon">
					<span><i class="icon ion-ios-search"></i></span>
				</div>
				<div class="yb-search-form-input">
					<input type="text" name="q" placeholder="Search here at yobuddy.com" autocomplete="off">
				</div>
				<div class="yb-search-form-spinner" id="yb-search-form-spinner">
					<span><img src="/assets/loading.gif" /></span>
				</div>
			</form>
		</div>
	</div>
	<div class="yb-search-result" id="yb-search-result"></div>
</section>

app/views/partials/_session.html.erb
<div class="yb-session-info">
	<div class="yb-session-image">
		<% if session_user.image? %>
			<%= image_tag session_user.image.url %>
		<% else %>
			<img src="/assets/default.jpg"/>
		<% end %>
	</div>
	<div class="yb-session-about">
		<h2><%= session_user.name %></h2>
		<h3 class="yb-username"><%= session_user.username %></h3>

		<div class="yb-session-address">
			<p><i class="icon ion-ios-email-outline"></i><%= session_user.email %></p>
			<p><i class="icon ion-ios-telephone-outline"></i>
				<% if session_user.number? %>
					<%= session_user.number %>
				<% else %>
					<a href="<%= session_edit_path %>">Add Phone Number</a>
				<% end %>
			</p>
			<p><i class="icon ion-ios-location-outline"></i><%= session_user.town %>, <%= session_user.country_name %></p>
		</div>
		<a class="yb-edit-user-link" href="<%= session_edit_path %>">Edit Profile</a>
		<div class="yb-item-data-menu">
			<ul id="yb-user-else-menu" data-id="<%= @activate %>">
				<li data-id="borrowed">
					<a href="<%=  session_borrowed_path %>">Lending</a>
					<span><%= @borrowed_count %></span>
				</li>
				<li data-id="borrowing">
					<a href="<%= session_borrowing_path %>">Borrowing</a>
					<span><%= @borrowing_count %></span>
				</li>
				<li data-id="favourites">
					<a href="<%= session_favourites_path %>">Favourites</a>
					<span><%= @favourites_count %></span>
				</li>
				<li data-id="requests">
					<a href="<%= session_requests_path %>">Requests</a>
					<span><%= @requests_count %></span>
				</li>
			</ul>
		</div>
		<div class="yb-session-about-edit">
			<a href="<%= session_logout_path %>" id="yb-session-logout">Log Out</a>
			<a href="#" id="yb-session-delete">Delete Account</a>
		</div>
	</div>
</div>
<div class="yb-session-add-item">
	<div class="yb-item-menu-list yb-menu-list" id="yb-menu-items-add-menu">
		<ul>
			<li><a href="<%= new_item_path %>?type=ajax" id="yb-add-item-new"><span class="item-icon"><i class="icon ion-ios-cart"></i></span><span class="item-text">Item</span></a></li>
			<li><a href="<%= new_item_request_path %>?type=ajax" id="yb-add-item-request-new"><span class="item-icon"><i class="icon ion-forward"></i></span><span class="item-text">Request</span></a></li>
		</ul>
	</div>
	<button id="yb-open-session-add-menu" data-id="add-menu">
		<i class="icon ion-android-add"></i>
	</button>
</div>

app/views/partials/_sidebar.html.erb
<section class="yb-left-navigation" id="yb-sidebar-ovarlay"></section>
<section class="yb-navigation-container" id="yb-sidebar-navigation">
	<% if is_logged_in? %>
		<div class="yb-sidebar-user">
			<div class="yb-notification">
				<span><i class="icon ion-ios-bell-outline"></i></span>
				<span id="yb-session-notifications" class="yb-header-tag" <% if session_user.notification_count <= 0 %> style="display: none;" <% end -%> ><%= session_user.notification_count %></span>
			</div>
			<% if session_user.image? %>
				<%= image_tag session_user.image.url, title: session_user.username %>
			<% else %>
				<img src="/assets/default.jpg" alt="Profile Image" title="<%= session_user.username %>" />
			<% end %>
			<h4><%= session_user.name %></h4>
			<p><%= session_user.email %></p>
		</div>
		<hr style="width: 100%;" />
	<% end %>
	<p><%= link_to "CATEGORIES", category_index_path %></p>
	<p><%= link_to "ITEMS", items_path %></p>
	<p><%= link_to "REQUESTS", item_requests_path %></p>
	<% if !is_logged_in? %>
		<p><a href="/user/new">SIGN IN</a></p>
	<% end %>
	<hr style="width: 100%;">
	<% if is_logged_in? %>
		<div class="yb-sidebar-menu-list">
			<ul>
				<li><a href="/session/items"><span class="item-icon"><i class="icon ion-ios-cart"></i></span><span class="item-text">Items</span></a></li>
				<li><a href="/session/requests"><span class="item-icon"><i class="icon ion-forward"></i></span><span class="item-text">Requests</span></a></li>
				<li><a href="/session/borrowed"><span class="item-icon"><i class="icon ion-ios-arrow-thin-right"></i></span><span class="item-text">Lending</span></a></li>
				<li><a href="/session/borrowing"><span class="item-icon"><i class="icon ion-ios-arrow-thin-left"></i></span><span class="item-text">Borrowing</span></a></li>
				<li><a href="/session/likes"><span class="item-icon"><i class="icon ion-ios-heart-outline"></i></span><span class="item-text">Likes</span></a></li>
				<li><a href="/session/favourites"><span class="item-icon"><i class="icon ion-ios-star-outline"></i></span><span class="item-text">Favourites</span></a></li>
				<li><a href="/session/followers"><span class="item-icon"><i class="icon ion-ios-arrow-thin-right"></i></span><span class="item-text">Followers</span></a></li>
				<li><a href="/session/following"><span class="item-icon"><i class="icon ion-ios-arrow-thin-left"></i></span><span class="item-text">Following</span></a></li>	
				<hr style="width: 100%;">
				<li><a href="/session/logout"><span class="item-icon"><i class="icon ion-log-out" style="color:red"></i></span><span class="item-text" style="color:red">Log Out</span></a></li>		
			</ul>
		</div>
	<% end %>
</section>