config/routes.rb
Rails.application.routes.draw do

    require 'sidekiq/web'
    require 'sidekiq/cron/web'

    mount Sidekiq::Web => '/admin/sidekiq/report'

    get '/404', to: 'error#not_found_error', as: 'not_found_error', via: :all
    get '/500', to: 'error#internal_server_error', as: 'internal_server_error', via: :all

    root 'home#index'
    get 'home/index'
    get 'search/all', to:'home#search', as: 'search'
    get 'search/items', to: 'home#search_items', as: 'search_items'
    get 'search/requests', to: 'home#search_requests', as: 'search_requests'
    get 'search/users', to: 'home#search_users', as: 'search_users'
    post 'notification/send', to: 'home#notification_getway', as: 'notification_getway'

    get '/session', to: 'session#index', as: 'session'
    get '/session/profile', to: 'session#index', as: 'session_profile'
    get '/session/items', to: 'session#index', as: 'session_items'
    get '/session/edit/get', to: 'session#edit', as: 'session_edit'
    get '/session/logout', to: 'session#logout', as: 'session_logout'
    patch '/session/update/image', to: 'session#update_image', as: 'session_update_image'
    patch '/session/update/info', to: 'session#update_info', as: 'session_update_info'
    patch '/session/update/credintials', to: 'session#update_credintials', as: 'session_update_credintials'
    patch '/session/update/address', to: 'session#update_address', as: 'session_update_address'
    patch '/session/update/contact', to: 'session#update_contact', as: 'session_update_contact'

    get '/session/lending', to: 'session#borrowed', as: 'session_borrowed'
    get '/session/borrowing', to: 'session#borrowing', as: 'session_borrowing'
    get '/session/favourites', to: 'session#favourites', as: 'session_favourites'
    get '/session/likes', to: 'session#likes', as: 'session_likes'
    get '/session/followers', to: 'session#followers', as: 'session_followers'
    get '/session/following', to: 'session#following', as: 'session_following'
    get '/session/requests', to: 'session#requests', as: 'session_requests'
    get '/notifications/all', to: 'session#notifications_all', as: 'notifications_all'
    get '/notifications/items-requests', to:'session#notifications_item', as: 'notifications_item'
    get '/notifications/borrow', to: 'session#notifications_borrow', as: 'notifications_borrow'
    get '/notifications/reminder', to: 'session#notifications_reminder', as: 'notifications_reminder'

    get '/session/report/:ressource_id/get', to: 'session#report_new', as: 'report_new'
    post '/session/report/post', to: 'session#report_create', as: 'report_create'

 
  	resources :items do
        resources :comments
        resources :item_borrow_user do
            resources :borrow_messages
        end
    end

    post '/item/:item_id/comment/create', to: 'comments#create', as: 'create_item_comment'
    patch '/item/:item_id/comment/:id/update', to: 'comments#update', as: 'update_item_comment'
    delete '/item/:item_id/comment/:id/delete', to: 'comments#destroy', as: 'delete_item_comment'
    post '/items/:item_id/item_borrow_user/:item_borrow_user_id/borrow_messages/send', to: 'borrow_messages#create', as: 'send_message'

    post '/item/create', to: 'items#create', as: 'item_create'
    post '/item/:id/update', to:'items#update', as: 'item_update'

    get '/item/:username/enc-dt-:uuid-:id', to: 'items#show', as: 'item_show'
    get '/item/:username/enc-dt-:uuid-:id/ajax', to: 'items#show_ajax', as: 'item_show_ajax'
    get '/item/:username/enc-dt-:uuid-:id/edit', to: 'items#edit', as: 'item_edit'
    get '/item/:username/enc-dt-:uuid-:item_id/borrow', to: 'item_borrow_user#new', as: 'borrow_item'
    get '/item/:username/enc-dt-:uuid-:id/available', to: 'items#available', as: 'item_available'

    get '/item/:username/enc-dt-:uuid-:item_id/borrows', to: 'item_borrow_user#index', as: 'item_borrows'
    get '/item/enc-dt-:uuid-:item_id-:id/borrow', to: 'item_borrow_user#show', as: 'item_borrow'
    get '/item/enc-dt-:uuid-:item_id-:id/borrow/review', to: 'item_borrow_user#borrow_review', as: 'borrow_review'
    post '/item/enc-dt-:uuid-:item_id/borrow/create', to: 'item_borrow_user#create', as: 'create_item_borrow'
    get '/item/enc-dt-:uuid-:item_id-:id/borrow/description', to: 'item_borrow_user#description', as: 'item_borrow_description'
    get '/item/enc-dt-:uuid-:item_id-:id/borrow/description/download.pdf', to: 'item_borrow_user#download_borrow_data', as: 'item_borrow_description_download'

    get '/item/enc-dt-:uuid-:item_id-:id/borrow/extend', to: 'item_borrow_user#extend', as: 'item_borrow_extend'
    post '/item/enc-dt-:uuid-:item_id-:id/borrow/extend/post', to: 'item_borrow_user#extend_borrow', as: 'extend_borrow_post'
    get '/item/enc-dt-:uuid-:item_id-:id/borrow/extend/status/update', to: 'item_borrow_user#update_borrow_extension_status', as: 'update_borrow_extension_status'
    get '/item/enc-dt-:uuid-:item_id-:id/borrow/renew', to: 'item_borrow_user#extend', as: 'item_borrow_renew'
    post '/item/enc-dt-:uuid-:item_id-:id/borrow/renew/post', to: 'item_borrow_user#renew_borrow', as: 'renew_borrow_post'

    get '/items/enc-dt-:uuid-:item_id-:item_borrow_user_id/follow-ups', to: 'item_borrow_user#follow_ups', as: 'follow_ups'
    get '/items/:item_id/borrow/:item_borrow_user_id/follow-ups/sent', to: 'item_borrow_user#load_follow_ups_sent', as: 'load_follow_ups_sent'
    get '/items/:item_id/borrow/:item_borrow_user_id/follow-ups/received', to: 'item_borrow_user#load_follow_ups_received', as: 'load_follow_ups_received'
    post '/items/:item_id/borrow/:item_borrow_user_id/follow-ups/send', to: 'item_borrow_user#send_follow_up', as: 'send_follow_up'

    get '/items/enc-dt-:uuid-:item_id-:item_borrow_user_id/messages/admin', to: 'borrow_messages#admin_messages', as: 'admin_messages'
    get '/items/enc-dt-:uuid-:item_id-:item_borrow_user_id/messages/admin/load', to: 'borrow_messages#load_admin_messages', as: 'load_admin_messages'
    post '/items/:item_id/borrow_item_user/:item_borrow_user_id/borrow_messages/images/send', to: 'borrow_messages#send_images', as: 'message_send_images'
    post '/items/:item_id/borrow_item_user/:item_borrow_user_id/borrow_messages/admin/send', to: 'borrow_messages#send_admin_message', as: 'message_send_admin'

    get '/items/requests/all', to: 'item_requests#index', as: 'item_requests'
    get '/items/request/:username/enc-dt-:uuid-:id', to: 'item_requests#show', as: 'item_request'
    get '/items/request/:username/enc-dt-:uuid-:id/ajax', to: 'item_requests#show_ajax', as: 'item_request_ajax'
    post '/items/request/:id/like', to: 'item_requests#like', as: 'item_request_like'
    get '/item/requests/new', to: 'item_requests#new', as: 'new_item_request'
    post '/item/requests/create', to: 'item_requests#create', as: 'create_item_request'
    get '/item/request/:username/enc-dt-:uuid-:id/edit', to: 'item_requests#edit', as: 'edit_item_request'
    get '/item/request/:item_request_id/image/:id/delete', to: 'item_requests#delete_item_request_image', as: 'delete_item_request_image'
    patch '/item/request/:id/update', to: 'item_requests#update', as: 'update_item_request'
    get '/item/request/:id/status/update', to: 'item_requests#update_request_status', as: 'update_item_request_status'
    delete '/item/request/:id/destroy', to: 'item_requests#destroy', as: 'destroy_item_request'
    get '/item/request/:username/enc-dt-:uuid-:id/suggestions/new', to: 'item_requests#suggestion_new', as: 'item_request_new_suggestion'
    get '/item/request/:username/enc-dt-:uuid-:id/suggestions/exist', to: 'item_requests#suggestion_exist', as: 'item_request_exist_suggestion'
    post '/item/request/:id/suggestions/create', to: 'item_requests#suggestion_create', as: 'item_request_create_suggestion'
    post '/item/request/:id/suggestions/create/exist', to: 'item_requests#suggesion_create_exist', as: 'item_request_create_exist_suggestion'
    get '/item/request/:id/suggestions/all', to: 'item_requests#suggestion_all', as: 'item_request_suggestions'
    get '/item/request/:item_request_id/suggestion/:id/edit', to: 'item_requests#suggestion_edit', as: 'item_request_suggestion_edit'
    patch '/item/request/:item_request_id/suggestion/:id/update', to: 'item_requests#suggestion_update', as: 'item_request_suggestion_update'
    get '/item/request/:item_request_id/suggestion/:id/status/update', to: 'item_requests#suggestion_update_status', as: 'item_request_suggestion_update_status'

    get '/items/:item_id/item_borrow_user/:item_borrow_user_id/all', to: 'borrow_messages#borrow_all', as: 'borrow_messages_all'
    get '/items/:item_id/item_borrow_user/:id/update_status', to: 'item_borrow_user#update_status', as: 'update_status'
    post '/items/:item_id/item_borrow_user/:id/update', to: 'item_borrow_user#update', as: 'update_item_borrow_item_user'
    get '/items/:item_id/item_borrow_user/:id/delete', to: 'item_borrow_user#destroy', as: 'destroy_item_borrow_item_user'

    post '/comments/:id/delete', to: 'comments#destroy', as: 'delete_comment'
    get '/item/:item_id/image/:id/delete', to: 'items#delete_image_item', as: 'delete_item_image'

    post '/item/:id/like', to: 'items#like_item', as: 'like'
    get '/item/:item_id/like/:id/destroy', to: 'items#like_item_destroy', as: 'like_destroy'
    post '/item/:id/favourite', to: 'items#favourite_item', as: 'favourite'
    get '/item/:item_id/favourite/:id/destroy', to: 'items#favourite_item_destroy', as: 'favourite_destroy'

    get '/users/all', to: 'user#index', as: 'users'

    resources :user

    get '/user/:username-:id/items', to: 'user#show', as: 'user_items'
    get '/user/:username-:id/likes', to: 'user#likes', as: 'user_likes'
    get '/user/:username-:id/followers', to: 'user#followers', as: 'user_followers'
    get '/user/:username-:id/following', to: 'user#following', as: 'user_following'
    get '/user/:username-:id/lending', to: 'user#borrowed', as: 'user_borrows'

app/views/item_borrow_user/_about.html.erb
<div class="yb-borrow-status">
	<div class="yb-status" id="yb-borrow-show-menu" data-id="borrow-s" style="background: <%= @borrow.check_expiration %>"></div>
	<div class="yb-borrow-menu yb-menu-list" id="yb-menu-items-borrow-s">
		<ul>
			<% if @borrow.check_expiration == "orange" %>
				<% if session_user.id == @borrow.user.id %>
					<li><a id="yb-edit-borrow-item" href="<%= edit_item_item_borrow_user_path(@borrow.item, @borrow) %>"><span class="item-icon"><i class="icon ion-edit"></i></span><span class="item-text">Update</span></a></li>
				<% elsif session_user.id == @borrow.item.user.id %>
					<li><a href="<%= update_status_path(@borrow.item, @borrow) %>?status=2" class="yb-update-borrow-status-link" data-status="rejected" data-borrow="<%= @borrow.id %>" data-item="<%= @borrow.item.id %>" data-url="<%= item_item_borrow_user_borrow_messages_path(@borrow.item, @borrow) %>" data-receiver="<% if session_user.id == @borrow.user.id %><%= @borrow.item.user.id %><% else %><%= @borrow.user.id %><% end %>" data-sender="<%= session_user.username %>" data-path="<%= item_borrow_path(@borrow.uuid, @borrow.item, @borrow) %>"><span class="item-icon"><i class="icon ion-close-round"></i></span><span class="item-text">Reject</span></a></li>
				<% end %>
			<% elsif @borrow.check_expiration == "lightgreen" %>
				<% if session_user.id == @borrow.last_update_user_id %>
					<li><a id="yb-edit-borrow-item" href="<%= edit_item_item_borrow_user_path(@borrow.item, @borrow) %>"><span class="item-icon"><i class="icon ion-edit"></i></span><span class="item-text">Update</span></a></li>
				<% else %>
					<li><a href="<%= update_status_path(@borrow.item, @borrow) %>?status=1" class="yb-update-borrow-status-link" data-status="accepted" data-borrow="<%= @borrow.id %>" data-item="<%= @borrow.item.id %>" data-url="<%= item_item_borrow_user_borrow_messages_path(@borrow.item, @borrow) %>" data-receiver="<% if session_user.id == @borrow.user.id %><%= @borrow.item.user.id %><% else %><%= @borrow.user.id %><% end %>" data-sender="<%= session_user.username %>" data-path="<%= item_borrow_path(@borrow.uuid, @borrow.item, @borrow) %>"><span class="item-icon"><i class="icon ion-checkmark-round"></i></span><span class="item-text">Accept</span></a></li>
					<li><a href="<%= update_status_path(@borrow.item, @borrow) %>?status=2" class="yb-update-borrow-status-link" data-status="rejected" data-borrow="<%= @borrow.id %>" data-item="<%= @borrow.item.id %>" data-url="<%= item_item_borrow_user_borrow_messages_path(@borrow.item, @borrow) %>" data-receiver="<% if session_user.id == @borrow.user.id %><%= @borrow.item.user.id %><% else %><%= @borrow.user.id %><% end %>" data-sender="<%= session_user.username %>" data-path="<%= item_borrow_path(@borrow.uuid, @borrow.item, @borrow) %>"><span class="item-icon"><i class="icon ion-close-round"></i></span><span class="item-text">Reject</span></a></li>
					<li><a id="yb-edit-borrow-item" href="<%= edit_item_item_borrow_user_path(@borrow.item, @borrow) %>"><span class="item-icon"><i class="icon ion-edit"></i></span><span class="item-text">Update</span></a></li>
				<% end %>
			<% elsif @borrow.check_expiration == "green" %>
				<% if session_user.id == @borrow.user.id %>
					<li><a href="#yb-borrow-qr-code" id="yb-borrow-get-qr-code"><span class="item-icon"><i class="icon ion-qr-scanner"></i></span><span class="item-text">Get Code</span></a></li>
					<% if @borrow.was_rendered %>
						<li><a href="<%= item_borrow_extend_path(@borrow.uuid, @borrow.item, @borrow) %>" id="yb-open-borrow-extend"><span class="item-icon"><i class="icon ion-arrow-expand"></i></span><span class="item-text">Extend</span></a></li>
					<% end %>
					<% if Array["returned", "succeeded"].include?(@borrow.status) %>
						<li><a href="<%= item_borrow_renew_path(@borrow.uuid, @borrow.item, @borrow) %>" id="yb-open-borrow-renew"><span class="item-icon"><i class="icon ion-refresh"></i></span><span class="item-text">Renew</span></a></li>
					<% end %>
					<li><a href="<%= report_new_path(@borrow.id) %>?ressource=borrow" id="yb-get-report"><span class="item-icon"><i class="icon ion-information-circled"></i></span><span class="item-text">Report</span></a></li>
				<% elsif session_user.id == @borrow.item.user.id %>
					<li><a href="#yb-borrow-qr-code" id="yb-borrow-get-qr-code"><span class="item-icon"><i class="icon ion-qr-scanner"></i></span><span class="item-text">Get Code</span></a></li>
					<% if @borrow.was_received and !@borrow.item.user.is_private? %>
						<li><a href="<%= follow_ups_path(@borrow.uuid, @item, @borrow) %>" id="yb-open-follow-ups"><span class="item-icon"><i class="icon ion-arrow-return-right"></i></span><span class="item-text">Follow Up</span></a></li>
					<% end %>
					<li><a href="<%= report_new_path(@borrow.id) %>?ressource=borrow" id="yb-get-report"><span class="item-icon"><i class="icon ion-information-circled"></i></span><span class="item-text">Report</span></a></li>
				<% end %>
			<% elsif @borrow.check_expiration == "red" %>
				<% if session_user.id == @borrow.user.id %>
					<li><a href="<%= destroy_item_borrow_item_user_path(@borrow.item, @borrow) %>?method=delete"><span class="item-icon"><i class="icon ion-trash-b"></i></span><span class="item-text">Delete</span></a></li>
					<li><a href="<%= item_borrow_renew_path(@borrow.uuid, @borrow.item, @borrow) %>" id="yb-open-borrow-renew"><span class="item-icon"><i class="icon ion-refresh"></i></span><span class="item-text">Renew</span></a></li>
					<li><a href="<%= report_new_path(@borrow.id) %>?ressource=borrow" id="yb-get-report"><span class="item-icon"><i class="icon ion-information-circled"></i></span><span class="item-text">Report</span></a></li>
				<% elsif session_user.id == @borrow.item.user.id %>
					<li><a href="<%= destroy_item_borrow_item_user_path(@borrow.item, @borrow) %>?method=delete"><span class="item-icon"><i class="icon ion-trash-b"></i></span><span class="item-text">Delete</span></a></li>
					<li><a href="<%= report_new_path(@borrow.id) %>?ressource=borrow" id="yb-get-report"><span class="item-icon"><i class="icon ion-information-circled"></i></span><span class="item-text">Report</span></a></li>
				<% end %>
			<% end %>
		</ul>
	</div>
</div>
<div class="yb-image">
	<% if session_user.id == @borrow.item.user.id %>
		<% if @borrow.user.image? %>
			<%= image_tag @borrow.user.image.url, alt: @borrow.user.username %>
		<% else %>
			<%= image_tag "/assets/default.jpg", alt: @borrow.user.username %>
		<% end %>
	<% else %>
		<% if @borrow.item.user.image? %>
			<%= image_tag @borrow.item.user.image.url, alt: @borrow.item.user.username %>
		<% else %>
			<%= image_tag "/assets/default.jpg", alt: @borrow.item.user.username %>
		<% end %>
	<% end %>
</div>
<div class="yb-info">
	<% if session_user.id == @borrow.item.user.id %>
	<h4><%= link_to @borrow.user.name, user_items_path(@borrow.user.username, @borrow.user), target: "_blank" %></h4>
	<% else %>
	<h4><%= link_to @borrow.item.user.name, user_items_path(@borrow.item.user.username, @borrow.item.user), target: "_blank" %></h4>
	<% end %>
	<p class="yb-item"><%= link_to @borrow.item.name, item_show_path(@borrow.item.user.username, @borrow.item.uuid, @borrow.item), target: "_blank" %></p>
	<p class="yb-date">
		<span><strong>From - </strong> <%= @borrow.from_date.localtime.strftime("%a %d %b, %Y at %H:%M") %></span>
		<span><strong> - To - </strong> <%= @borrow.to_date.localtime.strftime("%a %d %b, %Y at %H:%M") %></span>
	</p>
</div>
<div class="yb-about">
	<p class="yb-status-p">
		<span class="yb-status">Status - <span style="text-transform: capitalize;"><%= @borrow.status %></span></span>
		<span class="yb-menu" id="yb-borrow-menu-other" data-id="yb-other"><i class="icon ion-chevron-down"></i></span>
	</p>
	<div class="yb-borrow-menu-else yb-menu-list" id="yb-menu-items-yb-other">
		<ul>
			<li><a id="yb-open-borrow-item-description" href="<%= item_borrow_description_path(@item.uuid, @item, @borrow) %>"><span class="item-icon"><i class="icon ion-document"></i></span><span class="item-text">Description</span></a></li>
			<% if @borrow.user.id == session_user.id and !@borrow.item.user.is_private? %>
				<li><a href="<%= admin_messages_path(@borrow.uuid, @item, @borrow) %>" id="yb-open-admin-messages"><span class="item-icon"><i class="icon icon ion-ios-chatbubble-outline"></i></span><span class="item-text">Yo Buddy</span></a></li>
			<% end %>
			<li><a id="yb-open-borrow-item-review" href="<%= borrow_review_path(@borrow.uuid, @item, @borrow) %>?type=ajax"><span class="item-icon"><i class="icon ion-clipboard"></i></span><span class="item-text">Review</span></a></li>
			<li><a href="<%= report_new_path(@borrow.id) %>?ressource=borrow" id="yb-get-report-else"><span class="item-icon"><i class="icon ion-information-circled"></i></span><span class="item-text">Report</span></a></li>
		</ul>
	</div>
</div>

app/views/item_borrow_user/description.html.erb
<div class="yb-modal-container">
	<div class="yb-add-item yb-borrow-description">
		<h2>Borrow Item Description</h2>
		<div class="yb-item-image">
			<div class="yb-image-container">
				<%= image_tag @borrow.item.item_image[0].image.url, alt: @borrow.item.name %>
			</div>
		</div>
		<div class="yb-borrow-about" style="margin-top: -10px;">
			<%= render "item_borrow_user/descript" %>
		</div>
		<button type="button" id="yb-close-borrow-item-description" class="yb-btn-cancel">Cancel</button>
		<script type="text/javascript">$("#yb-close-borrow-item-description").closePopup();</script>
	</div>
</div>

app/views/item_borrow_user/edit.html.erb
<div class="yb-modal-container">
	<div class="yb-add-item">
		<% if @item_borrow.status != "failed" %>
			<h2>Edit Borrow Item</h2>
			<% if @active == true then %>
				<%= form_for :item_borrow, url: item_item_borrow_user_path(@item, @item_borrow) + ".json", method: :patch , html: {id: "yb-borrow-item", 'data-borrow': @item_borrow.id, 'data-item': @item.id, 'data-url': item_item_borrow_user_borrow_messages_path(@item, @item_borrow), 'data-receiver': @borrow_receiver, 'data-sender': session_user.username, 'data-path': item_borrow_path(@item_borrow.uuid, @item, @item_borrow),  } do |form| %>
					<div class="yb-add-price">
						<label>Propose Price :</label>
						<%= form.hidden_field :item_id, value: @item.id %>
						<%= form.hidden_field :last_update_user_id, value: session_user.id %>
						<%= form.hidden_field :status, value: @status[0] %>
						<%= form.number_field :price, min: '0', placeholder: 'Enter Price', required: true, value: @item_borrow.price, autocomplete: 'off' %>
						<%= form.select(:currency, required: true) do -%>
							<% @currencies.each do |currency| %>
								<% if @item_borrow.currency == currency["currency"] %>
								<%= content_tag(:option, currency["name"], value: currency["currency"], selected: "selected") %>
								<% else %>
								<%= content_tag(:option, currency["name"], value: currency["currency"]) %>
								<% end %>
							<% end %>
						<% end %>
						<%= form.select(:per, required: true) do %>
							<% @per.each do |t| %>
								<% if @item_borrow.per == t %>
								<%= content_tag(:option, "Per #{t}", value: t, selected: "selected") %>
								<% else %>
								<%= content_tag(:option, "Per #{t}", value: t) %>
								<% end %>
							<% end %>
						<% end %>
					</div>
					<div class="yb-from-date">
						<label>From & Times number :</label>
						<%= form.text_field :from_date, required:true, placeholder: "YYYY/MM/DD H:m", autocomplete: 'off' %>
						<%= form.number_field :numbers, required:true, min: '1', placeholder: "Enter Number of Times", autocomplete: 'off' %>
					</div>
					<label>Conditions :</label>
					<%= form.text_area :conditions, required: true %>
					<div class="yb-progress-bar-container" style="display: none;">
						<div class="yb-progress-bar" id="yb-borrow-progress-bar" data-value="20" data-max="100"></div>
					</div>
					<div style="display: block; position: relative;">
						<button type="submit" id="yb-submit-borrow">Submit</button>
						<button type="button" id="yb-close-borrow-item" class="yb-btn-cancel">Cancel</button>
					</div>
				<% end %>
				<script type="text/javascript">CKEDITOR.replace( 'item_borrow_conditions' );</script>
			<% else %>
				<p class="yb-error">YOUR PRIVATE ACCOUNT IS NOT ACTIVE</p>
				<button type="button" id="yb-close-borrow-item" class="yb-btn-cancel">Cancel</button>
			<% end %>
		<% else %>
			<p class="yb-error">YOU CANT UPDATE THIS BORROW REQUEST. STATUS : FAILED</p>
			<button type="button" id="yb-close-borrow-item" class="yb-btn-cancel">Cancel</button>
		<% end %>
	</div>
	<script type="text/javascript">
		$("#yb-close-borrow-item").closePopup();
		$("#item_borrow_per").changeItemPrice("item_borrow_price", "<%= @item.price %>", "<%= @item.per %>");
		$("#item_borrow_from_date").datetimepicker();
		$("#yb-submit-borrow").click(function(){
			for (instance in CKEDITOR.instances) {
	            CKEDITOR.instances[instance].updateElement();
	        }
		});
		$("#yb-borrow-item").updateBorrowItemUser();
	</script>
</div>

app/views/item_borrow_user/follow_ups.html.erb
<div class="yb-modal-container" style="width:45%;">
	<div class="yb-add-item">
		<div class="yb-borrow-admin-messages">
			<div class="yb-follow-ups-header">
				<% if is_admin_logged_in? %>
					<ul id="yb-follow-ups-header-menu">
						<li class="active"><a href="#" data-href="<%= load_follow_ups_received_path(@item, @borrow) %>">Sent</a></li>
						<li><a href="#" data-href="<%= load_follow_ups_sent_path(@item, @borrow) %>">Received</a></li>
					</ul>
				<% else %>
					<ul id="yb-follow-ups-header-menu">
						<li href="#" class="active"><a data-href="<%= load_follow_ups_sent_path(@item, @borrow) %>">Sent</a></li>
						<li><a href="#" data-href="<%= load_follow_ups_received_path(@item, @borrow) %>">Received</a></li>
					</ul>
				<% end -%>
			</div>
			<div class="yb-admin-messages-list">
				<div id="yb-admin-messages-list" data-yb="yb-admin-messages-<%= @borrow.id %>">
					<span class="yb-loading-spinner" style="margin-top: 50px;"><img src="/assets/loading.gif" /></span>
				</div>
			</div>
		</div>
		<% if @sender != 0 %>
			<div class="yb-admin-message-form">
				<%= form_for :follow_up, url: send_follow_up_path(@item, @borrow), html:{id: 'yb-admin-message-form', 'data-url': load_follow_ups_sent_path(@item, @borrow), 'data-sender': is_admin_logged_in? ? 'Yo Buddy' : session_user.username, 'data-receiver': is_admin_logged_in? ? @borrow.user.id : "admin_#{@borrow.admin.id}", 'data-id': @borrow.id, 'data-path': is_admin_logged_in? ? item_borrow_path(@borrow.uuid, @item, @borrow) : admin_borrow_path(@item, @borrow) } do |form| -%>
					<%= form.text_area :message, placeholder: 'Enter Message', autocomplete: 'off', style: "height: 46px;", required: true %>
					<div style="display: block; position: relative;">
						<button type="submit">Send</button>
						<button type="button" id="yb-close-admin-messages" class="yb-btn-cancel">Close</button>
					</div>
				<% end -%>
			</div>
		<% else -%>
			<div style="display: block; position: relative;">
				<button type="button" id="yb-close-admin-messages" class="yb-btn-cancel">Close</button>
			</div>
		<% end -%>
	</div>
	<script type="text/javascript">
		$(document).ready(function(){
			<% if is_admin_logged_in? %>
				setLoadData("yb-admin-messages-list", "<%= load_follow_ups_received_path(@item, @borrow) %>");
		    <% else %>
		    	setLoadData("yb-admin-messages-list", "<%= load_follow_ups_sent_path(@item, @borrow) %>");
		    <% end -%>
		    $("#yb-admin-messages-list").animate({ scrollTop: 100000000}, 1000);

		    $("#yb-follow-ups-header-menu li a").click(function(e){
		    	e.preventDefault();
		    	$("#yb-admin-messages-list").html('<span class="yb-loading-spinner" style="margin-top: 50px;"><img src="/assets/loading.gif" /></span>');
		    	setLoadData("yb-admin-messages-list", $(this).attr("data-href"));
		    	$(this).parent("li").addClass("active").siblings().removeClass("active");
		    	$("#yb-admin-messages-list").animate({ scrollTop: 100000000}, 1000);
		    });
		});
		$("#yb-close-admin-messages").closePopup();
		$("#yb-admin-message-form").adminTextMessage();
	</script>
</div>